# Generated by Django 4.1 on 2022-09-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVT', '0002_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='languages',
            name='text',
            field=models.CharField(max_length=600),
        ),
    ]
