# Generated by Django 4.1 on 2022-09-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVT', '0003_courses_alter_languages_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='instituicion',
            field=models.CharField(default='Coderhouse', max_length=50),
            preserve_default=False,
        ),
    ]
